version: "3"
services:
  clientemqtt:
    image: clientemqtt
    container_name: clientemqtt
    environment:
      - TZ=America/Argentina/Buenos_Aires 
      - SERVIDOR=${SERVIDOR} #Se reemplazará por la env var SERVIDOR defineda en .env
      - TOPICO=${TOPICO}
      - TOPIC1=${TOPIC1}
      - TOPIC2=${TOPIC2}
    restart: unless-stopped
